import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Playfair_Display_SC } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
});

const playfairSC = Playfair_Display_SC({
  variable: '--font-playfair-sc',
  subsets: ['latin'],
  weight: ['400', '700', '900'],
});

export const metadata: Metadata = {
  title: "Henning's Amazing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${geistMono.variable} ${geistSans.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

          <Header />

        {children}

          <Footer />

      </body>
    </html>
  );
}
